Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  # Ruduce this... Max: 15
  Max: 23

Metrics/ClassLength:
  Max: 131

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 125 # TODO: discuss and set this
  Exclude:
    - 'test/**/*.rb'

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
